apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-preprod
  namespace: preprod
spec:
  instances: 2 # 1 primary + 1 replica

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "512MB"
      effective_cache_size: "2GB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "4MB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"

  storage:
    size: 10Gi
    storageClass: local-path # k3s default, change to longhorn for production

  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

  bootstrap:
    initdb:
      database: appdb
      owner: appuser
      secret:
        name: postgres-preprod-credentials
