apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: preprod-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bakir004/kubernetes.git
    targetRevision: dev
    path: infra/overlays/preprod
  destination:
    server: https://kubernetes.default.svc
    namespace: preprod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
