apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bakir004/kubernetes.git
    targetRevision: main
    path: infra/overlays/test
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated: null # Disabled - no auto-sync for test environment
    syncOptions:
      - CreateNamespace=true
